s = set()
n = input("Enter the number:")
s.add(int(n))
n = input("Enter the number:")
s.add(int(n))
n = input("Enter the number:")
s.add(int(n))
n = input("Enter the number:")
s.add(int(n))
n = input("Enter the number:")
s.add(int(n))
n = input("Enter the number:")
s.add(int(n))
n = input("Enter the number:")
s.add(int(n))
n = input("Enter the number:")
s.add(int(n))
print(s)
